### ISSUE TITLE
aws-amplify 0.3.0: "Uncaught ReferenceError: require is not defined" when packaged with webpack

### ISSUE THREAD

**Issue by TheVaporTrail** [aws/aws-amplify#686] opened 2018-04-18 17:29 UTC
Do you want to request a feature or report a bug?
**Bug**

What is the current behavior?
**Absolutely minimal app (only uses 'import Amplify') results in browser [MacOS Chrome v65] _'Uncaught ReferenceError: require is not defined'_ error when loading page** 

**Chrome reports that the error is on the "require" line:**
```
, function(e, t, n) {
    "use strict";
    (function(e) {
        t.a = function(e, t) {
            return e instanceof t
        }
    }
    ).call(this, require("./../../process/browser.js"))
}
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

**package.json:**
```
{
  "name": "sampleProj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "aws-amplify": "^0.3.0",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.14"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack && cp -r ./dist/* ~/Sites/localhost/sampleProj/"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**index.js:**
```
import Amplify, { Analytics, Logger, Storage, Auth }  from 'aws-amplify';
import aws_exports from "./aws-exports";
```

**index.html:**
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>sampleProj</title>
	<script src="main.js"></script>
</head>
<body>
sampleProj
</body>
</html>
```

**Steps**
```
mkdir sampleProj && cd sampleProj
npm init -y
npm install webpack webpack-cli --save-dev
awsmobile init xxxxx
mkdir -p ~/Sites/localhost/sampleProj/
npm run build
```

What is the expected behavior?
**Successful start-up of Amplify code**

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
**Occurs with version 0.3.0. Does not occcur with 0.2.11**
**Tested only with MacOS Chrome v65**

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by richardzcode** [comment] 2018-04-18 17:47
Hey @TheVaporTrail what is your webpack config?

**Comment by TheVaporTrail** [comment] 2018-04-18 18:07
For _sampleProj_, I did not specify a webpack config; webpack is using its default config. I do have a webpack config for the new project that I created yesterday where I first encountered this problem; in that config I set _module.exports.target = web_ and also tried _module.exports.output.libraryTarget = umd_

Please let me know if there is a particular webpack config you would like me to test.

**Comment by glsorre** [comment] 2018-04-25 08:53
I have the same problem.

**Comment by roks0n** [comment] 2018-05-01 12:01
I'm having the same issue, also wanted to upgrade from `v0.2.15` to `v0.3.3`. Having the same error on `v0.3.0`

**Comment by roks0n** [comment] 2018-05-02 15:07
Just want to update that I've also bumped GraphQL from 0.13.1 to 0.13.2 but got the same error.

**Comment by 0x00A** [comment] 2018-05-02 15:27
Just tried to upgrade from `0.2.15` to `0.3.0` (also tried `0.3.3`) and everything breaks. The problem appears to be in the `graphql` module.

![image](https://user-images.githubusercontent.com/18703125/39531898-8763518c-4e2c-11e8-8907-fe239ff83d69.png)

**Comment by danielhep** [comment] 2018-05-06 18:08
Just wanted to say I have the exact same problem with the GraphQL module, even if I do not include it in my project.

**Comment by usamaejaz** [comment] 2018-05-08 15:05
I am also getting the same error.

**Comment by dreamniker** [comment] 2018-05-08 20:13
I am also getting the same error

**Comment by usamaejaz** [comment] 2018-05-08 20:16
I downgraded to 0.2.x for now and 0.2.x worked for me without this error.

**Comment by matt-erhart** [comment] 2018-05-08 23:41
Ran into this error as well, but I do want to use the simple graphql API bits.

**Comment by Stereobit** [comment] 2018-05-09 11:07
Same here :-/ I played with a bunch of webpack config changes but nothing helpt.

**Comment by Stereobit** [comment] 2018-05-09 11:35
Ok, I found something that helped. Graphql-js uses `.mjs` as file extension which caused issues with the webpack build. Adding

```{
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto",
}```

to my webpack rules helped.

**Comment by roks0n** [comment] 2018-05-09 11:59
I can confirm that was @Stereobit wrote also fixed my issue. Thanks!

**Comment by jordanranz** [comment] 2018-07-03 21:07
Closing this issue as there seems to be a valid fix. Please reopen this issue if the fix does not work or you have more questions.

**Closed by jordanranz** 2018-07-03 21:07 UTC
Labels: Build, question
