### ISSUE TITLE
'Sign in' button in Authenticator UI triggers error message

### ISSUE THREAD

**Issue by mbahar** [aws/aws-amplify#139] opened 2018-01-10 07:09 UTC
In React ;
Sign in action in Authenticator UI triggers following error message regardless of username/password: __WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function

I have used Mobile Hub generated aws-export.js with user Sign in enabled.

**Comment by jsancho** [comment] 2018-01-10 09:26
This could be a red-herring, but this exact same issue started happening to us only when making a production build* on the CI server with npm, i.e. `npm run build` 

The project was scaffolded with create-react-app.

The resolution was to use yarn 1.3.2 and creating a build with `yarn run build`.
This was rather tricky to debug as we could not reproduce the issue when running dev builds.

\* a "production build" in create-react-app bundles and minifies all js code into a single file

**Comment by jonsmirl** [comment] 2018-01-10 17:14
I can confirm this is a new bug.

I have both of the aws-sdk versions forced to match at 179. I still get the error.

**Comment by mbahar** [comment] 2018-01-10 19:48
@jsancho  I still got the same error after doing the following (yarn 1.3.2 ) 

1. rm -rf node_modules
2. yarn run build 
3. serve -s build

Any suggestions here?

**Comment by jsancho** [comment] 2018-01-10 21:33
@mbahar 
> Any suggestions here?
Maybe the fact that it worked for us with yarn instead of npm was a red herring indeed.

If I were to guess, I'd say that the new effort in reducing the dependencies has made something break during the bundling and minification process.

I'm new to React and webpack, so this is a bit beyond my level of skill at the minute.
If you are using create-react-app, you could always try to eject and turn off some of the steps that go into creating the production build. Somehow, try to find what is exactly happening to the internal dependencies to aws-sdk during the build process.

Alternatively, you could always revert back to amplify v0.1.30, which did not seem to have this problem...

**Comment by jonsmirl** [comment] 2018-01-10 23:28
This seems to be fixed now. aws-sdk was broken. A version has fixed it. 

My app is working again.

**Comment by richardzcode** [comment] 2018-01-11 18:16
@mbahar are you still getting the error? I'm not able to reproduce in my "create-react-app" test app. If still happening, could you run `npm list` to get dependency tree? It most likely pretty big so could you save to a file `npm list > dependencies.txt` then maybe create a gist?

**Closed** 2018-01-11 18:34 UTC

**Comment by mbahar** [comment] 2018-01-17 19:33
Fixed after the update.
