### ISSUE TITLE
Uncaught ReferenceError: global is not defined in latest Angular 6 RC

### ISSUE THREAD

**Issue by richardsengers** [aws/aws-amplify#678] opened 2018-04-17 13:05 UTC
**Do you want to request a feature or report a bug?**
Feature / Bug

**What is the current behavior?**
A dependencies of Buffer.js is causing an error on global node variable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
Create a new Angular cli 6 project and add AWS Cognito. Once you import aws-sdk or amazon-cognito-identity-js you'll get an error "Uncaught ReferenceError: global is not defined" from Buffer.js

**What is the expected behavior?**
Run an Angular 6 project without the dependency of the global node variable

I'm testing an Angular 6 app with AWS Cognito and noticed an error in my console.
> "Uncaught ReferenceError: global is not defined"

After some research I came acros this comment from the Angular CLI team 

https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 

I think when Angular 6 is released, this is going to be an issue

**Comment by glitchbane** [comment] 2018-04-22 19:37
Not sure what the status of this is, since it is marked as closed but the latest version does not have a fix.  #139 is referenced above, but 139 has a reference back to this issue.  Please clarify?

**Comment by richardsengers** [comment] 2018-04-23 07:37
Hi @glitchbane 
139 is an issue from another repo (Angular quicksrtart) which is closed in favor of this issue. This issue is still open though.

**Comment by CihanSari** [comment] 2018-04-25 11:56
Just for reference, I have passed through this issue with adding these lines on my index.html head:

  ```
<!-- https://github.com/aws/aws-amplify/issues/678 fix: -->
  <script>
    if (global === undefined) {
      var global = window;
    }
  </script>
  <!-- https://github.com/aws/aws-amplify/issues/678 fix end-->
```

**Comment by pdkpavankumar** [comment] 2018-05-11 18:12
@CihanSari The workaround you provided works 👍

**Comment by richardsengers** [comment] 2018-05-15 09:36
I think for now the best option would be to include 
```
(window as any).global = window;
```

In your polyfills.ts file, as mentioned here:
https://github.com/angular/angular-cli/issues/9827#issuecomment-386154063

**Comment by maxime1992** [comment] 2018-05-16 17:56
In case anyone is having that problem after upgrading to Angular 6 and using cognito, I've written a SO answer that might help: https://stackoverflow.com/a/50377270/2398593

**Comment by mlabieniec** [comment] 2018-05-16 20:00
We will add this to the polyfills within amplify

**Comment by haverchuck** [comment] 2018-05-29 22:32
We updated the Amplify documentation to describe how to fix this issue for an Angular 6 app.  A more permanent solution will be forthcoming when we are able to update dependencies.

**Closed by haverchuck** 2018-05-29 22:32 UTC
Labels: bug, documentation

**Comment by SebastianNiemann** [comment] 2018-10-11 13:00
It is the same for VuePress projects.

**Comment by appeality** [comment] 2019-03-18 20:11
> Just for reference, I have passed through this issue with adding these lines on my index.html head:
> 
> ```
> 
> <script>
>   if (global === undefined) {
>     var global = window;
>   }
> </script>
> 
> ```
If you use this approach, you must "add script-src unsafe-inline" to your CSP header, which is not ideal.

**Comment by francojay** [comment] 2019-04-24 14:04
When adding to polyfills and deploying to AWS via Code Pipeline. I get this

`Uncaught ReferenceError: require is not defined
    at Object.8xkj (main.c6634ac116c19c4a12a4.js:13010)
    at __webpack_require__ (runtime~main.740d6fd59d29f3f09e28.js:84)
    at Object.zKxw (main.c6634ac116c19c4a12a4.js:197325)
    at __webpack_require__ (runtime~main.740d6fd59d29f3f09e28.js:84)
    at Object.md97 (main.c6634ac116c19c4a12a4.js:173620)
    at __webpack_require__ (runtime~main.740d6fd59d29f3f09e28.js:84)
    at Object.Sp1i (main.c6634ac116c19c4a12a4.js:101990)
    at __webpack_require__ (runtime~main.740d6fd59d29f3f09e28.js:84)
    at Module.zUnb (main.c6634ac116c19c4a12a4.js:199199)
    at __webpack_require__ (runtime~main.740d6fd59d29f3f09e28.js:84)`

**Comment by 70R7** [comment] 2019-07-31 23:33
> Just for reference, I have passed through this issue with adding these lines on my index.html head:
> 
> ```
> 
> <script>
>   if (global === undefined) {
>     var global = window;
>   }
> </script>
> 
> ```

Thank you for this!

**Comment by jdnichollsc** [comment] 2019-09-27 03:52
awesome, thanks!

**Comment by linearza** [comment] 2019-12-29 12:35
Does this fix break source code highlighting in dev tools for anyone?

**Comment by 2RajShaikh** [comment] 2020-03-09 02:26
Still facing this issue on latest amplify version `aws-amplify: ^2.2.6` and Angular 8

> Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at Object.../../node_modules/aws-sdk/node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:83)
    at Object.../../node_modules/aws-sdk/lib/browserHashUtils.js (browserHashUtils.js:1)
    at __webpack_require__ (bootstrap:83)
    at Object.../../node_modules/aws-sdk/lib/browserHmac.js (browserHmac.js:1)
    at __webpack_require__ (bootstrap:83)
    at Object.../../node_modules/aws-sdk/lib/browserCryptoLib.js (browserCryptoLib.js:1)
    at __webpack_require__ (bootstrap:83)
    at Object.../../node_modules/aws-sdk/lib/browser_loader.js (browser_loader.js:4)
    at __webpack_require__ (bootstrap:83)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)

**Comment by hisham** [comment] 2020-06-13 19:07
+1. Still facing this issue with Angular 9 and aws-pubsub library (required by @aws-amplify/app library).

**Comment by emilio-martinez** [comment] 2020-08-10 01:03
The title of this issue is unfortunate because I don't think it has much to do with Angular at all. I just got this in a React application, and I think it largely depends on what the underlying bundler configuration is—in this case Webpack.

What's likely happening is that the dependency on `buffer` is bleeding into browser code as an external node dependency. In my case (your milage may vary), this resolved my issue:

```ts
// This causes an error
import { Amplify } from 'aws-amplify';

// This doesn't
import { Amplify } from '@aws-amplify/core';
```

So whether you get this error probably depends wether your the modules you import happen to bump into the usage of `buffer`. Polyfilling is probably an "okay" approach because [`buffer` is small](https://bundlephobia.com/result?p=buffer@5.6.0), but I really think this is a quality control issue with the `aws-amplify` package.

**Comment by silmat01** [comment] 2020-08-27 15:45
> It is the same for VuePress projects.

Is this issue fixed?

**Comment by emilio-martinez** [comment] 2020-09-04 08:28
> Is this issue fixed?

Nope.

**Comment by anthonyliriano** [comment] 2021-01-09 19:25
I'm seeing this issue on Angular 11...  the workaround seems to work
```
<!-- https://github.com/aws/aws-amplify/issues/678 fix: -->
<script>
  if (global === undefined) {
    var global = window;
  }
</script>
<!-- https://github.com/aws/aws-amplify/issues/678 fix end-->
```

**Comment by vildhjarta8** [comment] 2021-02-16 20:57
Angular 11, same issue

**Comment by AdonousTech** [comment] 2021-02-16 22:18
The workaround of adding the inline script is useless if you need the highest level CSP (which is a requirement). You should add to polyfills as specified by @richardsengers

**Comment by jsefiani** [comment] 2021-05-12 08:21
> The title of this issue is unfortunate because I don't think it has much to do with Angular at all. I just got this in a React application, and I think it largely depends on what the underlying bundler configuration is—in this case Webpack.
> 
> What's likely happening is that the dependency on `buffer` is bleeding into browser code within `aws-amplify`. In my case (your milage may vary), this resolved my issue:
> 
> ```ts
> // This causes an error
> import { Amplify } from 'aws-amplify';
> 
> // This doesn't
> import { Amplify } from '@aws-amplify/core';
> ```
> 
> So if you get this error, it probably depends on whether the modules imported happen to bump into the usage of `buffer`. I really think this is a quality control issue with the `aws-amplify` package.

This fixed my issue, thank you!

**Comment by jsefiani** [comment] 2021-05-12 08:52
Why is this issue closed?

**Comment by nazmifeeroz** [comment] 2021-05-22 14:33
2 years later since this issue was opened, I'm still seeing this error in React app.. 

I'm following the Amplify tutorials exactly.

Am i missing any sort of config?

**Comment by LumberSzquatch** [comment] 2021-06-18 15:10
@nazmifeeroz Same here, but in a Vue app. Maybe the issue runs deeper? I ended up stumbling upon this thread https://github.com/aws/aws-sdk-js/issues/3673. OP provided what I thought were some interesting nuggets of info. A similar solution to "fixing" the issue is provided there as well, so that may not be helpful; however, maybe it will help someone trying to refine their searching keywords.

**Comment by mgagna** [comment] 2021-06-25 11:11
Same problem still happening in June 2021
I'm using Vue.js 3
Package versions:
- "aws-amplify": "4.1.2",
- "vue": "3.1.2",
- "typescript": "4.3.4",
- "vite": "2.3.8",

This workaround from @CihanSari worked well, even using Auth from Amplify.

> Just for reference, I have passed through this issue with adding these lines on my index.html head:
> 
> ```
> 
> <script>
>   if (global === undefined) {
>     var global = window;
>   }
> </script>
> 
> ```

Why is this closed?

**Comment by JuniorDEVed** [comment] 2021-07-04 16:21
Why close the issue when it isn't solved. Looking to move away from the amplify stack if this keeps happening!

**Comment by 0x6c23** [comment] 2021-07-09 14:45
Have the same issue using Vue 3

**Comment by craigchandler** [comment] 2021-08-02 12:12
thought i'd give amplify a go with Angular 12. Hit this error straight away, Is Amplify useless given this bugs response?

**Comment by jiahao-c** [comment] 2022-01-04 03:50
Having the same issue using
```json
"dependencies": {
    "aws-amplify": "^4.3.11",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.0.7",
    "typescript": "^4.4.4",
    "vite": "^2.7.2"
  }
```

**Comment by jmhmd** [comment] 2022-01-09 15:21
Getting the same error, but with @aws-sdk/client-s3

Using:

- "vue": "^3.2.26"
- "vite": "^2.7.9"
- "@vitejs/plugin-vue": "^1.10.2"
- "@aws-sdk/client-s3": "^3.45.0"

Same workaround header script gets rid of the error, but annoying and wasted a lot of time trying to figure out what was wrong.

**Comment by k-vikram** [comment] 2022-04-17 18:02
Same workaround for vite + react + TS projects!

**Comment by dsriniv** [comment] 2022-07-12 15:56
Angular 13 still facing the same issue. I tried adding polyfill.ts with `(window as any).global = window;`. But nothing seems to be working.

**package.json**
```
"@aws-amplify/auth": "^3.4.16"
```

**Comment by Sife-ops** [comment] 2022-08-29 08:54
Echoing my disappointment. Aws-amplify basically unusable without workarounds in a Vite project due to `ReferenceError: global is not defined`.

**Comment by abdallahshaban557** [comment] 2022-08-31 11:06
@Sife-ops  - can you please try the workaround mentioned in this comment. Does it resolve your issue? https://github.com/aws-amplify/amplify-js/issues/10242#issuecomment-1223074932

**Comment by markhker** [comment] 2022-09-01 23:43
This comment [#10242 (comment)](https://github.com/aws-amplify/amplify-js/issues/10242#issuecomment-1223074932) worked for me in my Vite project

**Comment by abdallahshaban557** [comment] 2022-09-02 20:08
That is awesome @markhker  - thank you for confirming it! 

@Sife-ops - any updates on your end? @dsriniv - can you also try the workaround mentioned above?

**Comment by abdallahshaban557** [comment] 2022-09-18 09:46
Hi @shmert - did you try the recommendation mentioned in this comment? https://github.com/aws-amplify/amplify-js/issues/10242#issuecomment-1223074932

**Comment by lucatsf** [comment] 2022-09-29 00:01
@CihanSari thanks man

**Comment by ZalgirisKaunas** [comment] 2023-02-14 22:02
still doesn't work with vue 3 and quasar

**Comment by nadetastic** [comment] 2023-02-14 23:13
Hi @ZalgirisKaunas to clarify, is the workaround mentioned not working for you with Vue3/Quasar?

**Comment by ZalgirisKaunas** [comment] 2023-02-15 07:30
```
  if (global === undefined) {
    var global = window;
  }
```

Only adding this to index.html worked

**Comment by nadetastic** [comment] 2023-02-15 16:31
Got it, thanks for the update and glad you were able to get it working

**Comment by nadetastic** [comment] 2023-02-15 16:31
Got it, thanks for the update and glad you were able to get it working @ZalgirisKaunas

**Comment by mclean25** [comment] 2023-02-21 23:58
> Same workaround works well _vite + react + TS projects_!
> 
> **Update:**
> 
> Found a better better fix for **Vite Projects**. Edit the `vite.config.[js/ts]` file with the following:
> 
> ```
> export default defineConfig({
>   define: {
>     "global": {},
>   },
> });
> ```
> 
> Works like a charm!

I had this working for Vite as well, until it caused me a separate issue with Axios where it expected the `global` object to be something different. Also got working by adding this after `<head>` in `index.html`

```html
<script>
  if (global === undefined) {
    var global = window;
  }
</script>
```

**Comment by CaffGeek** [comment] 2023-05-10 15:41
> Have angular 15 and latest version of amplify still stuck. Tried all the solutions none of them work, no script in index, no polyfills , nothing!

Same w Angular 16

**Comment by nadetastic** [comment] 2023-05-10 15:53
@DavithkbY could you please open a new issue with additional context/information on what you are seeing? Thanks!

**Comment by DavithkbY** [comment] 2023-05-11 07:05
> @DavithkbY could you please open a new issue with additional context/information on what you are seeing? Thanks!

I finally managed to fix it! 
So I was not including polyfill file everywhere. For angular you need to include it in:
tsconfig.spec.json as :
`  "files": [
    "src/polyfills.ts"
  ],`

in tsconfig.app.json as:
`  "files": [
    "src/polyfills.ts"
  ],`

In angular.json in BOTH (!!IMPORTANT!!) builder for TEST and EVERY OTHER BUILDER.
So in Angular.JSON Search for "polyfills" everywhere and include the file !!!

My polyfills.ts file which works:
`(window as any).global = window;

(window as any).process = {
  env: { DEBUG: undefined },
};`

So just to conclude, I hadn't included the damn polyfills file in every location needed. No one on the internet either told me to include it in the tsconfig files and the other builds(which in hindsight seems pretty logical..)
**I hope you guys can get your apps fixed too!**

**Comment by DavithkbY** [comment] 2023-05-11 07:10
> 

Could you please check my fix on the post above

**Comment by DavithkbY** [comment] 2023-05-11 07:10
> > Have angular 15 and latest version of amplify still stuck. Tried all the solutions none of them work, no script in index, no polyfills , nothing!
> 
> Same w Angular 16

Could you please check my fix on the post above

**Comment by bilalakkari** [comment] 2024-02-04 15:48
> In case anyone is having that problem after upgrading to Angular 6 and using cognito, I've written a SO answer that might help: https://stackoverflow.com/a/50377270/2398593

Thank you man... i really appreciate it.
