### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function error when signin is called

### ISSUE THREAD

**Issue by rayhaanq** [aws/aws-amplify#260] opened 2018-02-11 09:26 UTC
I think there was a similar issue here: #224 but I'm not using the react library. These are my dependencies:
```
"dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.5.3",
    "@ionic-native/splash-screen": "4.5.3",
    "@ionic-native/status-bar": "4.5.3",
    "@ionic/storage": "2.1.3",
    "@types/node": "^9.4.4",
    "aws-amplify": "^0.2.4",
    "aws-sdk": "^2.192.0",
    "cordova-android": "7.0.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.2.0",
    "enum-values": "^1.2.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "4.0.0-13",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.8",
    "lodash": "^4.17.4",
    "typescript": "2.7.1"
  }
```
The error message:
```
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function
    at AuthenticationHelper.generateRandomSmallA (AuthenticationHelper.js:90)
    at new AuthenticationHelper (AuthenticationHelper.js:42)
    at CognitoUser.authenticateUser (CognitoUser.js:216)
    at Auth.js:270
    at new t (polyfills.js:3)
    at AuthClass.signIn (Auth.js:269)
    at AuthProvider.webpackJsonp.53.AuthProvider.login (auth.ts:28)
    at LoginPage.webpackJsonp.522.LoginPage.login (login.ts:34)
    at Object.eval [as handleEvent] (LoginPage.html:31)
    at handleEvent (core.js:13255)
```
The error occurs when the `signIn` method is called (simplified version of my code)
```
import Amplify, {Auth} from 'aws-amplify';
import aws_exports from './../../aws-exports';

Amplify.configure(aws_exports);

login(user: User) {
	return Auth.signIn(user.username, user.password);
}
```
Any ideas how this can be fixed? Thanks

**Comment by powerful23** [comment] 2018-02-11 19:19
@rayhaanq could you remove that aws-sdk dependency or make it to 2.177.0?

**Comment by mlabieniec** [comment] 2018-02-11 19:19
@rayhaanq The issue is the aws-sdk version that you have included:

    "aws-sdk": "^2.192.0",

The version of the cognito-identity-js sdk is currently incompatible with that aws-sdk version. we are pushing a fix to this next week that will fix this, but if you are including the aws-sdk on your own as well (as in your dependencies) you will need to pin it at:

    "aws-sdk": "2.177.0"

**Comment by mlabieniec** [comment] 2018-02-13 18:00
@rayhaanq this issue is fixed in latest aws-amplify and amazon-cognito-identity-js 2.0. If you install the latest aws-amplify you should get the latest cognito as well. Please let us know if you still see the issue.

**Closed by mlabieniec** 2018-02-13 18:00 UTC
