### ISSUE TITLE
Pinpoint 415 error

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#440] opened 2018-03-13 06:24 UTC
Today 415 error occurred in all my applications (Preflight OPTIONS request to AWS pinpoint when I call Amplify.configure(...)). It looks like something was changed in AWS Pinpoint API because I did not change anything.

```
Request URL:https://pinpoint.us-east-1.amazonaws.com/v1/apps/28608fdeb0a242808717d3062672b53c/endpoints/us-east-1%3Ae6c0af2c-0d66-49dc-be85-ad506b4ec2b2
Request Method:OPTIONS
Status Code:415 Unsupported Media Type
```

Request headers:
```
OPTIONS /v1/apps/28608fdeb0a242808717d3062672b53c/endpoints/us-east-1%3Ae6c0af2c-0d66-49dc-be85-ad506b4ec2b2 HTTP/1.1
Host: pinpoint.us-east-1.amazonaws.com
Connection: keep-alive
Access-Control-Request-Method: PUT
Origin: http://localhost:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Access-Control-Request-Headers: authorization,content-type,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
```

Response headers:
```
HTTP/1.1 415 Unsupported Media Type
Content-Type: application/json
Content-Length: 37
Connection: keep-alive
Date: Tue, 13 Mar 2018 06:04:02 GMT
x-amzn-RequestId: 543b2205-2684-11e8-ab34-2f34995da5b5
X-Cache: Error from cloudfront
Via: 1.1 cab1caa227c8742f20858daf99f9c3ea.cloudfront.net (CloudFront)
X-Amz-Cf-Id: qJPQzUbMxy-jmHfEL3SEd1QgduBw7pVD0HP5-zHjt7ZG3oJU4SLuSg==
```

Response body:
`{"message": "Unsupported Media Type"}`

**Comment by retwedt** [comment] 2018-03-13 16:06
Same thing happened to me.  Please advise.

**Comment by bbernays** [comment] 2018-03-13 18:44
I am seeing this same thing.

I think this is a duplicate of issue #438

**Comment by richardzcode** [comment] 2018-03-13 21:35
Issue fixed on the service side. @ildar-icoosoft @retwedt could you have a try now?

**Comment by bbernays** [comment] 2018-03-13 21:36
@richardzcode I can confirm I am not seeing the error anymore

**Comment by richardzcode** [comment] 2018-03-13 21:57
Great! Thanks @bbernays !

**Closed** 2018-03-13 21:58 UTC
Labels: investigating

**Comment by retwedt** [comment] 2018-03-13 22:07
Thanks!

**Comment by ildar-icoosoft** [comment] 2018-03-14 05:35
Thank you!
