### ISSUE TITLE
Cannot get API.get to work

### ISSUE THREAD

**Issue by marioskonstantinou** [aws/aws-amplify#127] opened 2018-01-08 17:40 UTC
Hello,

I'm trying to use API.get and pass queryStringParameters in the request so these params can be accessed from Lambda function's 'event' but this doesn't seem to work.

```
    const val1 = 'test123';
    const val2 = 'test123';

    let myInit = {
        'queryStringParameters': {
            'key1': val1,
            'key2': val2
        },
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }
    };

    return API.get(apiName, path, myInit).then(data => {
        return data;
    }).catch(err => console.log('error.', err));

```

Notes:
1. I've added the query params in Api Gateway method (URL Query String Parameters)
2. In Lambda function's logs i can see `queryStringParameters: null,`
3. API Gateway Integration request details (Use Lambda Proxy integration is enabled)
![image](https://user-images.githubusercontent.com/2276860/34683665-616414c4-f4ab-11e7-9839-5155660d6a0e.png)
4. I've tried adding the query params as part of path as abc?key1=val1&key2=val2 etc. but didn't work as well
5. API.post works good (when passing the params in body

Let me know if you need more details

Thanks in advance.

**Comment by powerful23** [comment] 2018-01-09 23:20
@marioskonstantinou did you use mobile hub and awsmobile cli to create the Api and lambda functions?

**Comment by marioskonstantinou** [comment] 2018-01-10 20:04
@powerful23 I'm using mobile hub with API Gateway and Lambda functions yes. What is not supported ? API.get or passing query parameters?

**Comment by powerful23** [comment] 2018-01-10 21:37
@marioskonstantinou passing query parameters

**Comment by marioskonstantinou** [comment] 2018-01-11 07:08
@powerful23 Any plans on releasing this anytime soon? It's quite an important feature of the API

**Comment by mlabieniec** [comment] 2018-01-11 18:56
@marioskonstantinou did you use the cli to init your project? i.e. `awsmobile init` or did you use Mobile Hub console and create your lambda function yourself? The reason i ask is because the awsmobile cli provides your lambda sample with the express framework which requires you to do a few things to receive the queryStringParameters, see here for example:
https://github.com/awslabs/aws-serverless-express#getting-the-api-gateway-event-object

**Comment by marioskonstantinou** [comment] 2018-01-13 16:20
@mlabieniec I've created a new project through Mobile Hub along with Cloud Logic (API, Lambda functions etc.). Then i've linked (with the awsmobile cli commands) my (existing) react-native project with the project i've created in Mobile Hub.

**Comment by lichao0817** [comment] 2018-01-19 01:58
@marioskonstantinou I have problem with passing the query parameters as well. I think the only workaround we can do is to dump everything into the url.

**Comment by marioskonstantinou** [comment] 2018-01-19 06:39
@lichao0817 I've tried that already and it didn't work. If you have a working example, would u mind sharing it here?

**Comment by lichao0817** [comment] 2018-01-19 17:13
suppose that your path is `const path = '/users';`, if you want to include a param called email you simply append the param to the path. Now it becomes
`const path = '/users?email=example@email.com';`

**Comment by chapeljuice** [comment] 2018-01-25 17:13
Thanks @lichao0817 for that work around ... I can't believe the `queryStringParameters` object isn't supported ... kind of important to be able to send parameters easily via a GET.

**Comment by chapeljuice** [comment] 2018-01-25 17:19
@marioskonstantinou I have a React Native example here that should work until `queryStringParameters` is supported:

```
const apiName = 'http://myendpoint.com'
const path = `/my/path?param1=${value1}&param2=${value2}`
API.get(apiName, path)
    .then((response) => {
        resolve(response)
    },
    (err) => {
        console.log('err resp', err)
        resolve(err)
    })
```

**Comment by chapeljuice** [comment] 2018-01-25 19:09
Eh, for anyone who's still following (@lichao0817 @marioskonstantinou) I may have spoke too soon ... now I'm getting the error about the request signature calculation being off. :(

**Comment by chapeljuice** [comment] 2018-01-25 21:25
Okay so a colleague of mine figured out that the parameter values need to be URL encoded for this to work. I had a colon (`:`) in one of my values which resulted in me getting that signature calculation error.

Once I url encoded the colon (to `%3A`), the request returned a successful response.

Hope this helps anyone!

**Comment by vadiraja** [comment] 2018-01-30 10:44
I am also getting Invalid Signature error with url query string parameters. No error if I pass queryString as Init {} options. But I don't get these query string in lambda functions (via APIG->Lambda Integration)

**Comment by nuttmeister** [comment] 2018-02-21 12:04
Having this problem as well, is there anyway to get this working?
If I add the query string to the path I always get an signature error, regardless of if I urlencode it or not.

**Comment by chapeljuice** [comment] 2018-02-21 15:03
@nuttmeister do you have the latest release? Try that if not.

**Comment by nuttmeister** [comment] 2018-02-26 08:46
@chapeljuice yes, I'm using version 0.2.7.

**Comment by nuttmeister** [comment] 2018-02-26 15:48
Should have a fix ready soon (today) that adds support for supplying query string parameters via url and through queryStringParameters in init obj.

The problem now is that Amplify is calculating the hash on path = /path?query=string where aws strips away the query strings (like it should) from the url and only calculates path = /path.

In the fix you can also mix and match supplying via path or init obj.

**Comment by nuttmeister** [comment] 2018-02-27 16:58
I know have a working fix that does the following. Just need to write some tests for it to go through.

But basically you can supply query strings via path or by init obj. Both will work at the same time.

It will uri encode the query strings and add to the signer using rfc3986 so that it works with characters like ' etc, that are not encoding with standard encodeURIComponent etc.

It will tranform the url + path to not include the query strings but move them to the axios clients params object which will handle encoding for the query strings when sending the request.

I will see tonight if I have the time to finish all the tests or not. I have tried it quite a lot today.
So anyone need tro try a quick fix just let me know.

**Comment by lzbikowski** [comment] 2018-03-16 22:24
Hi there, 
any chance to get that merged ?
It's very disturbing miss...

**Comment by leezen** [comment] 2018-04-05 17:35
Relatedly, it doesn't appear that the SDK is properly encoding path parameters either. For example, if a path parameter has a '%' or '@' in it, the signature will be incorrect and the request will fail.

**Comment by nuttmeister** [comment] 2018-04-05 17:38
Sorry for the late reply, I have been away for a while. I will try to update the coverage this weekend so the PR can be merged. The fix should fix the %, @ as well.

Have you tried the PR manually @leezen ?

**Comment by leezen** [comment] 2018-04-05 19:38
Are you referring to this PR? https://github.com/aws/aws-amplify/pull/378/files -- if so, I think it won't address the problem I'm mentioning because nothing is touching the path segments. Referring to https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html -- the path segments must be URI encoded. So I think you would need to also apply fixed_encodeURIComponent to each of the path parts before signing.

**Comment by causingchaos2** [comment] 2018-04-05 19:45
I can confirm this works fine: 
```
`API.post('trips', '/days', { body: { content: "this is some text', imageURL: 'image-s3-url' } } )`

//then on the other side using serverless-webpack, you can simply parse the variables out by doing:
const data = JSON.parse(event.body)
console.log(data.content)
console.log(data.image-s3-URL)
```
You can easily pull out stuff from the body.

However, this does not work: 
`return API.get('trips','/days', {'queryStringParameters': {'param1': "99b60260-363c-11e8-b7ca-250a890d0675"}})` 

This will ALWAYS send a null parameter for the JSON object, whether it be body, or queryStringParameter JSON object.

and event.queryStringParameter  will == null on the API side of your code.

**Comment by causingchaos2** [comment] 2018-04-05 19:46
I hope they add this to amplify soon! :) ... Appending the query parameters is fine for now I guess.

**Comment by nuttmeister** [comment] 2018-04-05 19:52
@leezen ahhh, ok. yeah, it's just going to be uriencoded by axios default uri encoding. so will not work in that case.

i can add the fixed uri encoding to the path segment as well this weekend if that will make you happy :P

**Comment by leezen** [comment] 2018-04-05 20:03
Sure! That will save me from having to make an additional PR :) Looking forward to seeing the change merged in!

**Closed** 2018-05-05 23:11 UTC
Labels: API, feature-request
