### ISSUE TITLE
ConsoleLogger getItem failed! TypeError: Cannot read property 'getItem' of null

### ISSUE THREAD

**Issue by edzillion** [aws/aws-amplify#828] opened 2018-05-12 11:21 UTC
**Do you want to request a feature or report a bug?**
A bug (I think). This is a react-native project. 

**What is the current behavior?**

```
$ npm test

> circles-mobile@0.1.0 test E:\dev\circles\circles-mobile
> jest

 PASS  __tests__\App.test.js
  √ renders without crashing (141ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.094s
Ran all test suites.
  console.warn node_modules\aws-amplify\lib\Common\Logger\ConsoleLogger.js:84
    [WARN] 42:19.64 Cache - getItem failed! TypeError: Cannot read property 'getItem' of null

  console.warn node_modules\aws-amplify\lib\Common\Logger\ConsoleLogger.js:84
    [WARN] 42:19.79 Cache - setItem failed! TypeError: Cannot read property 'getItem' of null
```
**Steps to reproduce**
```
$ git clone https://github.com/CirclesUBI/circles-mobile.git
$ cd circles-mobile
$ npm install
$ npm test
```

**What is the expected behavior?**
I am pretty sure that it should be showing the aws-amplify initialisation logs from `Amplify.configure(awsExports)`

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

Not sure. Running on Windows 8.1. 

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**

Output is same as above.

This looks a lot like this issue:

* [Android Webview: “Uncaught TypeError: Cannot read property 'getItem' of null”](https://stackoverflow.com/questions/33079762/android-webview-uncaught-typeerror-cannot-read-property-getitem-of-null#33080057)

* [ERROR/Web Console: Uncaught TypeError: Cannot call method 'getItem' of null at http://m.youtube.com/:844](https://stackoverflow.com/questions/5822256/error-web-console-uncaught-typeerror-cannot-call-method-getitem-of-null-at-h)

which is because 'WebView' doesn't have `setDomStorageEnabled` set to `true`:

> WebSettings settings = webView.getSettings();
>  settings.setDomStorageEnabled(true);

I know react-native uses `UIWebView`, but I am not sure if it is used in this context?  Any help appreciated.

**Comment by edzillion** [comment] 2018-05-14 08:47
```
"devDependencies": {
    "env-ci": "^2.1.0",
    "jest-expo": "~27.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
 },
"dependencies": {
    "aws-amplify": "^0.3.3",
    "aws-amplify-react-native": "^0.2.9",
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2"
  }
```

**Comment by edzillion** [comment] 2018-05-14 21:47
Yes. Happens both locally and on Travis.

I have run a stacktrace: 

```
Trace
        at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Common\Logger\ConsoleLogger.js:81:19)
        at ConsoleLogger.Object.<anonymous>.ConsoleLogger.warn (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Common\Logger\ConsoleLogger.js:151:19)
        at BrowserStorageCache.Object.<anonymous>.BrowserStorageCache.getItem (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Cache\BrowserStorageCache.js:341:20)
        at AWSAnalyticsProvider.<anonymous> (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Analytics\Providers\AWSAnalyticsProvider.js:352:66)
        at step (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Analytics\Providers\AWSAnalyticsProvider.js:32:23)
        at Object.next (E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Analytics\Providers\AWSAnalyticsProvider.js:13:53)
        at E:\dev\circles\circles-mobile\node_modules\aws-amplify\lib\Analytics\Providers\AWSAnalyticsProvider.js:7:71
        at tryCallTwo (E:\dev\circles\circles-mobile\node_modules\promise\lib\core.js:45:5)
        at doResolve (E:\dev\circles\circles-mobile\node_modules\promise\lib\core.js:200:13)
        at new Promise (E:\dev\circles\circles-mobile\node_modules\promise\lib\core.js:66:3)

with a bit of investigating the problem is that `endpointId` is not in the cache when `AWSAnalyticsProvider` tries to retrieve it. I have checked the cache and it is definitely not there. I am next going to try run this on a fresh `create-react-native-app`.
```

**Comment by hardchor** [comment] 2018-06-05 17:52
@edzillion Did running this from a fresh install solve your problems?

**Comment by edzillion** [comment] 2018-06-05 19:56
I never did run it again; had to attend to other things. You can close this and if I can recreate I will come back.

**Comment by richardzcode** [comment] 2018-06-08 21:04
This was caused by using localStorage in node env. Should be fixed already.

**Closed by richardzcode** 2018-06-08 21:04 UTC
Labels: investigating

**Comment by musso** [comment] 2018-07-03 10:09
@richardzcode , still got the same problem using aws-amplify v0.4.9-unstable.0 in angular SSR. May I know if it was fixed in aws-amplify-react-native only?
