### ISSUE TITLE
Amplify not working with APIGateway and CloudFront Domains - First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by BerndWessels** [aws/aws-amplify#283] opened 2018-02-13 23:25 UTC
Route53 `mydomain.com` > CloudFront > APIGateway `myapi`

`Amplify.API` throws and exception `First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`

Basically its not possible to use `Amplify` to call APIs that are behind CloudFront and a custom domain.

This is a very very common thing I guess and really hope its a priority to be fixed.

It certainly disrupts our efforts at the moment to move big chunks of our applications to AWS.

**Comment by powerful23** [comment] 2018-02-14 00:48
@BerndWessels thank you for your feedback. So you are using the API category to make a request to the endpoint which is 'mydomain.com'? How does your APIGateway configured? Is it restricted to authenticated user?

**Comment by jonsmirl** [comment] 2018-02-14 02:27
Dupe of #106

**Comment by mlabieniec** [comment] 2018-02-14 20:22
@BerndWessels just curious, are you using API Gateway to create the custom domain? I.e. 

https://console.aws.amazon.com/apigateway/home?region=us-east-1#/custom-domain-names

It seems as though you are creating the distro and route53 record manually, is there a reason you are not doing this through API Gateway custom domains if so?

I'm going to run a few tests and see what we can do either way (we do have custom domains with api gateway currently in our backlog is why I'm asking)

**Comment by BerndWessels** [comment] 2018-02-14 20:32
@mlabieniec I am pretty sure the "Create Custom Domain Name" via APIGateway is just AWS Console sugar and creates exactly the same - an A Record and a CF Distribution with a ACM certificate.

I am creating these via terraform myself to have more control and total automation and reproducability of my infrastructure.

The actual issue is with `aws-amplify` code like shown in #106 

This code does NOT work with custom domains!

```js
var parse_service_info = function (request) {
    var url_info = url.parse(request.url), host = url_info.host;
    var matched = host.match(/([^\.]+)\.(?:([^\.]*)\.)?amazonaws\.com$/);
    var parsed = (matched || []).slice(1, 3);
    if (parsed[1] === 'es') {
        parsed = parsed.reverse();
    }
    return {
        service: request.service || parsed[0],
        region: request.region || parsed[1]
    };
};
```

**Comment by mlabieniec** [comment] 2018-02-14 20:43
Gotcha, I'm not sure if that is all the api gateway portion does, but i'll look into it. We are working on custom domains and trying to coordinate an update with support in cloud logic. We'll keep this thread updated.

**Comment by BerndWessels** [comment] 2018-02-14 22:08
I just hacked around a bit. One simple thing you could do is change `aws-amplify\packages\aws-amplify\src\API\RestClient.ts` to include optional `service` and `region` parameter properties.

```js
    /**
    * Basic HTTP request. Customizable
    * @param {string} url - Full request URL
    * @param {string} method - Request HTTP method
    * @param {json} [init] - Request extra params
    * @return {Promise} - A promise that resolves to an object with response status and JSON data, if successful.
    */
    async ajax(url: string, method: string, init) {
        logger.debug(method + ' ' + url);

        const parsed_url = this._parseUrl(url);

        const params = {
            method,
            url,
            host: parsed_url.host,
            path: parsed_url.path,
            headers: {},
            data: null,
        ////////////////////////////////////////////////////////////// >
            service: null,
            region: null
        ////////////////////////////////////////////////////////////// <
        };

        let libraryHeaders = {};

        if (Platform.isReactNative) {
        const userAgent = Platform.userAgent || 'aws-amplify/0.1.x';
            libraryHeaders = {
                'User-Agent': userAgent
            };
        }

        const extraParams = Object.assign({}, init);

        if (extraParams.body) {
            libraryHeaders['content-type'] = 'application/json; charset=UTF-8';
            params.data = JSON.stringify(extraParams.body);
        }

        ////////////////////////////////////////////////////////////// >
        params.service = extraParams.service;
        params.region = extraParams.region;
        ////////////////////////////////////////////////////////////// <

        params.headers = { ...libraryHeaders, ...extraParams.headers };

        // Do not sign the request if client has added 'Authorization' header,
        // which means custom authorizer.
        if (params.headers['Authorization']) { return this._request(params); }

        return Auth.currentCredentials()
            .then(credentials => this._signed(params, credentials));
    }
```

This allows for calls to APIs behind custom domains like this:

```js
    let myInit = {
      body: {
        somebody: 'peabody'
      },
      headers: {},
      service: 'execute-api',
      region: 'us-east-1'
    };
    API.post(apiName, path, myInit).then(response => {
```

This works fine but results in another problem - the call gets through, even OPTIONS works fine but the AWS_IAM protected POST endpoint now returns:

`message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."`

So somewhere else in the code needs to be some more modifications for custom domains to be done.

@mlabieniec @powerful23 @jonsmirl Any idea where?

**Comment by jonsmirl** [comment] 2018-02-15 00:21
@BerndWessels 

> I am pretty sure the "Create Custom Domain Name" via APIGateway is just AWS Console sugar and creates exactly the same - an A Record and a CF Distribution with a ACM certificate.

The pricing is not exactly the same when you build it out of the pieces. 

Also, I suspect long term APIGateway may simply disappear and turn into lambda@edge functions.

**Comment by vadiraja** [comment] 2018-02-18 18:52
I am also facing same issue. Since Apple Store requires ipv6 support for urls, we are forced set up custom domain with Cloud Front distribution with ip6 support. Now we can't use Amplify for making API calls with Custom Domain set up.
I am curious as how other people have overcome to make AWS API Gateway, Amplify a production viable mobile backend option.

**Comment by mlabieniec** [comment] 2018-02-19 16:43
@vadiraja we have a fix coming for this to pass and use a custom domain that should come this week. I'll also raise this with the API Gateway team as part of a feature request/issue for ipv6 support thanks for your feedback!

**Closed** 2018-02-19 21:05 UTC
Labels: enhancement

**Comment by vadiraja** [comment] 2018-02-20 01:32
@mlabieniec Thank you for the consideration
