### ISSUE TITLE
forceAliasCreation defaults to true when calling confirmSignup, opposing what the AWS docs say, and there is no way to edit this value.

### ISSUE THREAD

**Issue by VicFrolov** [aws/aws-amplify#679] opened 2018-04-17 16:10 UTC
### Do you want to request a feature or report a bug?

bug

### What is the current behavior?

When calling confirmSignUp, forceAliasCreation seems to be set to true, with no ability to set it to false. The docs state "By default set to False", but with amplify it seems to be set to true. This makes me very nervous to use this in production.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Sign up some user A via phone or email verification (only tested with phone number), and have phone number set as an alias in your user pool. Sign up some other user B, with the same phone number. 

### What is the expected behavior?

After entering a confirmation code, a  `forceAliasCreation` error should be thrown. Unfortunately, this seems to migrate the previous alias to the new user. Not aligned with the AWS documentation.

### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

aws-amplify: 0.2.14
ios 11

**Comment by quangv** [comment] 2018-04-25 01:04
dupe of #449 - agreed `forceAliasCreation` should be `false` like it is in [cognito identity](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmSignUp.html#API_ConfirmSignUp_RequestSyntax), or at least have an option to toggle.

**Closed** 2018-06-13 17:30 UTC
Labels: Auth, investigating
