### ISSUE TITLE
Cognito-Identity Use Case 24 does not work

### ISSUE THREAD

**Issue by BoneyAz** [aws/aws-amplify#360] opened 2018-02-25 05:13 UTC
The following code as per use case 24 for amazon-cognito-identity-js does not return any data:

`cognitoUser.getMFAOptions(function(err, mfaOptions) {
        if (err) {
            alert(err);
            return;
        }
        console.log('MFA options for user ' + mfaOptions);
    });`

Returns

`MFA options for user undefined`

I checked the underlying GetUser method is not returning MFAOptions or PreferredMfaSetting as documented here: [https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html](url) regardless of the MFA configuration of my user. My user pool is configured with optional software based TOTP MFA.

**Comment by yuntuowang** [comment] 2018-02-26 18:58
Hi @BoneyAz, I cannot open the URL you mentioned. 
Please check here: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html

Response Elements:
If the action is successful, the service sends back an HTTP 200 response.

The following data is returned in JSON format by the service.

MFAOptions
Specifies the options for MFA (e.g., email or phone number).

Type: Array of MFAOptionType objects

PreferredMfaSetting
The user's preferred MFA setting.

Type: String

UserAttributes
An array of name-value pairs representing user attributes.

For custom attributes, you must prepend the custom: prefix to the attribute name.

Type: Array of AttributeType objects

UserMFASettingList
The list of the user's MFA settings.

Type: Array of strings

Username
The user name of the user you wish to retrieve from the get user request.

Type: String

Length Constraints: Minimum length of 1. Maximum length of 128.

Pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+

**Comment by teddarling** [comment] 2018-02-28 19:49
I've seen the issue as well. The issue is that there are no options if using Software (TOTP) token. There are only options for phone, email.

Essentially, if using TOTP, then the API really has no way to tell if the user has anything enabled until login time and the user is directed to enter their software code.

**Comment by yuntuowang** [comment] 2018-02-28 21:38
Hi @teddarling, yes, when using TOTP, the API has no way to tell if the user has anything enabled until login. 
You can see the detailed process here in "TOTP Software Token MFA" section: 
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa.html

**Comment by powerful23** [comment] 2018-03-28 05:18
Closing the issue. Please feel free to reopen if necessary.

**Closed by powerful23** 2018-03-28 05:18 UTC
Labels: investigating
