### ISSUE TITLE
Storage.put() method adds 'public/' prefix to key

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/aws-amplify#396] opened 2018-03-02 11:01 UTC
Do you want to request a feature or report a bug? bug

What is the current behavior?

I'm trying to upload file to S3. Here is my code:
Storage.put('aaa', body, {})
aws-amplify transforms the key to 'public/aaa'

What is the expected behavior?
aws-cmplify should not change the Key

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? aws-amplify 0.2.7

**Comment by mlabieniec** [comment] 2018-03-02 16:18
Duplicate of #332  we are working on making this configurable. Currently it places the configured permission level as the prefix i.e. public/private

**Closed by mlabieniec** 2018-03-02 16:18 UTC

**Comment by Shuvo-Hoque** [comment] 2020-11-23 20:05
Try it this way : 

await Storage.put(filename, file, {
                    contentType: 'application/pdf',
                    customPrefix: {
                        public:''
                     } 
                }).then(result => {
                    console.log(result)
                }).catch(err => {
                    console.log(err)
                    alert(`Can't upload file: ${err}`)
                });

filename : this is the s3_key of your file. so when you'll upload the file, the file will be saved in S3 bucket in this name.

**Comment by Shuvo-Hoque** [comment] 2020-11-23 20:06
Found a way to do this,

let result = await Storage.put('folderName/imageName.png', blob, {
  contentType: 'image/jpeg',
    customPrefix: {
       public:''
    }
 });
This saves the file in the root of the bucket, inside folder "folderName".

**Comment by SomnathS09** [comment] 2021-07-09 17:54
what about downloading then, Storage.list() returns empty array and if files are placed in "public" named directory then it returns the files
