### ISSUE TITLE
Multipart upload support for Storage class?

### ISSUE THREAD

**Issue by snapcoyote** [aws/aws-amplify#495] opened 2018-03-22 00:27 UTC
Is it possible to use the storage class 'put' method to do a multipart upload?

**Comment by powerful23** [comment] 2018-03-23 23:49
Closed as a duplicate of #61

**Comment by manueliglesias** [comment] 2018-03-24 01:52
I haven't tested this, but I think multipart should be working for files with a size > 5mb

- Storage is using the S3 client to do a `s3.upload()`
https://github.com/aws/aws-amplify/blob/2e83916927c64946dd51d931395e742b53556971/packages/aws-amplify/src/Storage/Storage.ts#L172

- That one, in turn uses `AWS.S3.ManagedUpload`
https://github.com/aws/aws-sdk-js/blob/5880e725ca12f559fcead5cac2c305e55de1ccfb/lib/services/s3.js#L1066-L1067

- which uses the managed uploader, that automatically does multi-art for files greater than 5mb
https://github.com/aws/aws-sdk-js/blob/d3f0701e8aff9697231f023d2e5a5c289a8ec8ec/lib/s3/managed_upload.js#L145

**Closed** 2018-03-24 04:12 UTC
Labels: question

**Comment by ajhool** [comment] 2018-12-08 06:44
I believe you need to alter the S3 CORS configuration in the backend to enable multipart upload -- I provided a process to do this in #61 . It's very quick and appears to be working.
