### ISSUE TITLE
Amplify.configure()'s cognito call fails when user-signin does not support unauth users

### ISSUE THREAD

**Issue by ceich** [aws/aws-amplify#293] opened 2018-02-15 19:30 UTC
Minor bug: shows up in the web console as a failed POST:
```
POST https://cognito-identity.us-east-2.amazonaws.com/ 400 (Bad Request)
```
Steps:
- Configure a MobileHub project with the User sign-in feature enabled and required.
- Add a web app to the project, initialize with `create-react-app` and `awsmobile pull`
- Add `Amplify.configure(awsmobilejs)` as usual.
- Run `npm start` and examine the web console.

I would expect Amplify to notice that sign-in is required, and not attempt any Cognito calls prior to sign-in.

Amplify 0.2.6 does not seem to use the `aws_mandatory_sign_in` element of `aws-exports.js`.

**Comment by powerful23** [comment] 2018-02-15 21:36
@ceich thanks for your feedback!

**Comment by powerful23** [comment] 2018-02-20 20:15
@ceich this bug has been fixed in the latest release. Please feel free to reopen the issue if neccessary.

**Closed by powerful23** 2018-02-20 20:15 UTC
Labels: bug

**Comment by ceich** [comment] 2018-02-21 05:16
I no longer see this at configure() time, but do see this and another error at federated login time. Do you want me to submit a new issue, or to reopen this one?

**Comment by crysislinux** [comment] 2018-02-21 13:28
I do see this when call 
```
AwsAuth.configure({
  identityPoolId: 'xxx',
  region: 'xxx',
  userPoolId: 'xxx',
  userPoolWebClientId: 'xxx',
  mandatorySignIn: false,
});
```

if I don't pass identityPoolId, I would not see the error. The problem is that I cannot know what's wrong here, the body of the 400 response is just an alien string to me

**Comment by crysislinux** [comment] 2018-02-21 13:46
It seems that I should set mandatorySignIn to true, then the error will go.

**Comment by jnreynoso** [comment] 2018-07-01 23:29
+1

**Comment by powerful23** [comment] 2018-07-02 17:53
It's because if you have the identitypoolId then Amplify will automatically try to get a guest credentials for you which will lead to that http request failing because you didn't turn the mandatorySignIn to true.

**Comment by SplicePHP** [comment] 2018-08-31 05:04
Could not find any the mandatory option.

This is what worked for me:
in: amplify/backend/auth/[PROJECT]/parameters.json
set: "allowUnauthenticatedIdentities": true

**Comment by powerful23** [comment] 2018-08-31 16:47
@SplicePHP it's in the configuration: https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#manual-setup
