### ISSUE TITLE
Appsync subscriptions not working

### ISSUE THREAD

**Issue by mg131** [aws/aws-amplify#660] opened 2018-04-15 03:01 UTC
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Running a fresh Angular application with no other dependencies aside from `aws-amplify@0.3.0` and type definitions to get the package to work: `@types/paho-mqtt@1.0.3`, `@types/zen-observable@0.5.3`, and `@types/node@6.0.106`.

I'm not sure if I missed anything here but when using the API module to subscribe to AppSync, subscription data is not received. I followed the documentation here: [https://github.com/aws/aws-amplify/blob/master/docs/media/api_guide.md](url). Tried to do a basic subscription that prints to the console newly added users.

GraphQL Subscription:
'subscription AddedUser {
    addedUser {
      userID,
      userFirstName,
      userLastName
    }
  }';

Code:
`const subscription = API.graphql(graphqlOperation(UserService.AddedUser)) as Observable<object>;`
`subscription.subscribe({
  next: (eventData) => console.log(JSON.stringify(eventData))
 });`

I've already tried the same subscription on the AppSync console and can confirm that it does work. I just can't get it to work in the Angular application.

Plus the documentation guide is slightly off: queries and mutations are passed in the `API.graphql()` function while subscriptions are passed in the `API.graphqlSubscribe()` function. Though during my usage, there is no `graphqlSubscribe()` available in the API module (at least not publicly available). What I did notice though is that the `graphql()` function returns an object of type `Promise<GraphQLResult>` or `Observable<object>` (I should be using this for all operations, right?). A Promise object is returned when passing query/mutations while an Observable object is returned when passing subscriptions.

**What is the expected behavior?**
Subscriptions should receive data changes from mutations.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
Version: aws-amplify@0.3.0
Browser: Chrome
OS: Windows 10

**Comment by manueliglesias** [comment] 2018-04-16 10:57
Hi @mg131, thanks for pointing out the docs error, as you correctly mention, `API.graphqlSubscribe()` doesn't exist, the correct one for all GraphQL operations is `API.graphql()`.

Regarding not receiving data, can you verify in your network tab of the developer tools that a network request to start the subscriptions handshake is made and that a websocket connection is opened?

**Comment by mg131** [comment] 2018-04-17 02:57
Hey @manueliglesias, I took a look at the network tab and yes, a network request was sent.

Image of network request here (XHR tab):
[https://imgur.com/Die7CTK](url)

But it doesn't seem to create a websocket to the subscription.

Image of websockets in Chrome here (WS tab):
[https://imgur.com/TJwR9I5](url)

This is pretty much the only code I did for Amplify. Am I doing something wrong here? No results, no errors, nothing.
```
import { Component, OnInit } from '@angular/core';
import { API, graphqlOperation } from 'aws-amplify';
import { GraphQLResult } from 'aws-amplify/lib/API/types';
import * as Observable from 'zen-observable';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  private static UserSubscription: string = `subscription {
    addedUser {
      userID,
      userFirstName,
      userLastName
    }
  }`;

  ngOnInit() {
    const observable: Observable<object> = API.graphql(graphqlOperation(AppComponent.UserSubscription)) as Observable<object>;
    observable.subscribe({
      next: (value: object) => {
        console.log(JSON.stringify(value));
      },
      error: (error: any) => {
        console.log(JSON.stringify(error));
      }
    });
  }

}
```

I was able to get subscriptions working by creating a new Angular application. This time the only dependencies are: `aws-appsync@1.0.15` and `graphql-tag@2.8.0`. The rest are Angular default packages. Results are now printed to the Chrome console when I execute mutations in AppSync console.

Here is an image of a websocket created by aws-appsync (WS tab):
[https://imgur.com/OhjDQFO](url)

Notes: Mutations and Queries do work in Amplify. I've already tested them.

**Comment by karlmosenbacher** [comment] 2018-04-17 07:27
Im facing the same issue with aws-amplify-react-native library. Queries works fine, but I cannot use subscriptions. When I try subscriptions in the AppSync console it works fine.

**Comment by manueliglesias** [comment] 2018-04-19 10:08
@mg131 @karlmosenbacher 

I couldn't reproduce the issue you are seeing, I created a small codesandbox with working vanilla js code. I would suggest looking closely at how Amplify is being configured there.

The code assumes a schema from the sample API in the AppSync console, but shouldn't be too complex to adapt to yours.

[![Edit 3yq2nkv2p](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3yq2nkv2p?autoresize=1&hidenavigation=1&module=%2Fsrc%2Findex.js)

![codesandbox](https://user-images.githubusercontent.com/6154160/38985245-2a6e648e-43c9-11e8-88f1-e1211a88a3a4.jpeg)

**Comment by karlmosenbacher** [comment] 2018-04-19 16:36
@manueliglesias thanks! I'll take a look

**Comment by mlabieniec** [comment] 2018-04-20 20:53
Reopening so we can capture some of this in documentation. @mbahar fyi

**Comment by mbahar** [comment] 2018-04-20 21:54
Ok. I noted this one. Closing.

**Closed by mbahar** 2018-04-20 21:54 UTC
Labels: GraphQL, documentation
